version: '3'

services:

  db_patient:
    image: mysql:8
    container_name: db_patient
    volumes:
      - db_patient:/db_patient/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mediscreenpatient

  patient_service:
    image: 'docker-patient-service'
    build:
      context: ./Patient-service
    container_name: patientservice
    depends_on:
      - db_patient
    ports:
      - 8080:8080
    links:
      - db_patient:patient_service
    restart: on-failure
    networks:
      - mediscreen

  ui:
    image: 'docker-ui'
    build: ./UI
    container_name: ui
    ports:
      - 9001:9001
    networks:
      - mediscreen

networks:
  mediscreen:

volumes:
  db_patient: